#!/usr/bin/env bash
LC_ALL=C
set -e

local_branch="$(git rev-parse --abbrev-ref HEAD)"
# feat/harchizi
valid_branch_regex="^(feat|fix|imp|hot)\/[A-Za-z0-9._-]+$|^develop$"

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

FILES=` git status --porcelain | grep -E '^[AM] +(app|config|database|resources|routes|public|tests|modules)/.*\.php$' | cut -c 4- | tr '\n' ' '`
if [ -z "$FILES" ]
then
    echo "No php files found in commit."
else
    echo ${FILES}
    docker compose exec -T -u bita bitoff-admin composer phpcs --verbose ${FILES}
    git add ${FILES}
fi
